// Frases tiernas sobre parejas sanas y felices. Rotan en el inicio cada 5s.
export const FRASES_AMOR = [
  'Nos elegimos de nuevo cada mañana.',
  'Volver a casa es volver a vos.',
  'Tu mano busca la mía sin pensarlo.',
  'Dos personas enteras que se eligen cada día.',
  'Cada día te vuelvo a elegir, sin que nadie nos obligue.',
  'Te cebé el mate como te gusta, sin preguntar.',
  'Hay un amor que se cocina lento. El nuestro es de esos.',
  'Sos la persona con la que más me río.',
  'Tu abrazo de la mañana arregla el día.',
  'Nos hicimos hogar el uno del otro, sin apuro.',
  'Con vos respiro distinto: en casa.',
  'Cocinar juntos es nuestra forma de charlar.',
  'Nos reímos de lo mismo a las dos de la tarde.',
  'Tu calma me ordena cuando ando hecho un lío.',
  'Lo que tenemos no se encontró: lo fuimos haciendo.',
  'Sos mi plan favorito, incluso sin plan.',
  'Anoche nos dormimos hablando, otra vez.',
  'Acá podés ser vos, sin recortarte.',
  'Tenemos un idioma que armamos entre los dos.',
  'Crecemos sin soltarnos la mano.',
  'Me corrés el pelo de la cara y me derrito.',
  'Nos decimos las cosas; no hace falta adivinar.',
  'Aburrirnos juntos también es un buen plan.',
  'Lo nuestro es calma que abriga, no euforia.',
  'Te guardo el último mordisco sin que lo pidas.',
  'Te admiro un poco más en cada cosa chiquita que hacés.',
  'Nos repartimos la manta sin pelear.',
  'Saber que estás es mi lugar más calmo.',
  'Caminamos al mismo paso sin acordarlo.',
  'Te cuento lo feo y seguís ahí, tranqui.',
  'Lo nuestro es liviano, como un buen martes.',
  'Una mirada y ya nos estamos riendo.',
  'Compartir el silencio también es estar juntos.',
  'Cada año me gustás de una manera nueva.',
  'Nuestros mejores momentos no salen en fotos.',
  'Nos cuidamos sin pedirlo, casi sin darnos cuenta.',
  'Me gusta quién soy cuando estamos en calma.',
  'Confiar es saber que no tengo que estar atenta.',
  'Sabés cómo tomo el café, y eso me abriga.',
  'Aprendimos a querernos mejor con el tiempo.',
  'Construimos algo nuestro, de a poco y a propósito.',
  'Nos contamos el día como si fuera noticia.',
  'Con vos el silencio también es compañía.',
  'Hay días en que te quiero todavía más que ayer.',
  'Nos cargamos con cariño todo el día.',
  'Crecemos cada uno y, sin querer, crecemos juntos.',
  'Me guardás un lugar tibio en la cama.',
  'El amor que dura es el que se sigue cuidando.',
  'Reírnos de nada es nuestra especialidad.',
  'Acá nadie tiene que fingir estar bien.',
]
