// Frases motivadoras para una pareja sana: recordatorios y empujoncitos para
// cuidar el vínculo y amarse más cada día. Rotan en el inicio cada 5s.
export const FRASES_AMOR = [
  'Elijámonos hoy otra vez',
  'Antes de asumir, preguntemos',
  'Discutamos el problema, no a nosotros',
  'Reparar vale más que tener razón',
  'Lo que se agradece, crece',
  'Escuchar para entender, no para responder',
  'Después de la pelea, el abrazo encuentra el camino',
  'Pidamos perdón sin esperar quedar a mano',
  'Tomemos aire antes de tirar la primera palabra',
  'Lo que callamos pesa; hablémoslo suave',
  'Preguntar cómo estás también es amor',
  'Demos el beneficio de la duda primero',
  'Una charla a tiempo evita un nudo',
  'Un buen reclamo empieza sin reproche',
  'Volvamos a hablar cuando baje la marea',
  'Decir lo que siento nos acerca',
  'Pedir lo que necesito no es de menos',
  'Hablemos del roce antes de que crezca',
  'Digamos lo lindo en voz alta',
  'Bajemos la voz y subamos la ternura',
  'La paciencia también es una forma de querer',
  'Del lado del otro, no enfrente',
  'Equipo, siempre',
  'Crezcamos juntos, sin marcador',
  'Crecer cada uno nos hace mejores juntos',
  'Cuidemos esto que armamos entre los dos',
  'Dediquémonos un rato sin pantallas hoy',
  'El cariño se cuida en los días comunes',
  'Hoy mirá lo que sí',
  'Nombrá hoy una cosa linda del otro',
  'Un gracias a tiempo abriga',
  'Agradecer en voz alta cambia el día',
  "Decir 'qué bueno que estás' también es amor",
  'Mirá lo que el otro hace sin que se lo pidan',
  'Lo que celebramos juntos, se queda',
  'Celebremos lo chiquito, que de eso se hace lo grande',
  'Que el cariño se note, no solo se sienta',
  'Volvamos a empezar las veces que haga falta',
  'Perdonar es soltar la cuenta, no olvidar',
  'Acompañarnos en el cambio es seguir eligiéndonos',
  'Quedarse también es una forma de elegir',
  'Lo que se riega todos los días, florece',
  'Hagamos del nosotros un lugar al que volver',
  'Estar presentes hoy vale más que prometer siempre',
  'Renovemos el sí en lo chico de cada día',
  'Cada uno entero, los dos eligiéndose',
  'El tiempo del otro también es nuestro tiempo',
  'Tener ganas hoy también es amarnos',
  'Acordáte de por qué lo elegís',
  'Mirá lo que tenemos antes de pedir más',
]
